# backend/app/models/test_blueprint.py

import uuid
from datetime import datetime

from sqlalchemy import (
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Text
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship

from app.database import Base


class TestBlueprint(Base):
    """
    Represents an AI-generated test plan for a specific API version.

    A TestBlueprint:
    - Is generated by AI (Gemini)
    - Must be approved before execution
    - Produces one or more TestRuns
    """

    __tablename__ = "test_blueprints"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        index=True
    )

    api_version_id = Column(
        UUID(as_uuid=True),
        ForeignKey("api_versions.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # AI-generated testing strategy (structured JSON)
    ai_strategy_json = Column(
        JSONB,
        nullable=False
    )

    # Approval status
    status = Column(
        Enum(
            "PENDING_APPROVAL",
            "APPROVED",
            "REJECTED",
            name="test_blueprint_status_enum"
        ),
        default="PENDING_APPROVAL",
        nullable=False,
        index=True
    )

    # Optional: human-readable summary generated by AI
    summary = Column(
        Text,
        nullable=True
    )

    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False
    )

    approved_at = Column(
        DateTime,
        nullable=True
    )

    # Optional: user who approved the blueprint
    approved_by = Column(
        UUID(as_uuid=True),
        nullable=True
    )

    # -----------------------------
    # Relationships
    # -----------------------------

    api_version = relationship(
        "ApiVersion",
        back_populates="test_blueprints"
    )

    test_runs = relationship(
        "TestRun",
        back_populates="blueprint",
        cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return (
            f"<TestBlueprint "
            f"id={self.id} "
            f"status={self.status}>"
        )
