// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css"; // Ensure this path points to where your globals.css actually is (e.g., ./globals.css or ../styles/globals.css)
// // @ts-ignore: allow importing global css without type declarations
// import "../styles/globals.css"; 

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// // import "./globals.css"; // Ensure this path points to where your globals.css actually is (e.g., ./globals.css or ../styles/globals.css)
//  @ts-ignore: allow importing global css without type declarations
import "./globals.css";

// 1. Load the "Inter" font (Professional & Clean)
const inter = Inter({ subsets: ['latin'] })

// 2. SEO Metadata
export const metadata: Metadata = {
  title: 'ApiScan | Autonomous AI QA Engineer',
  description: 'Automated API testing powered by AI. Upload Swagger, get bugs.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      {/* 3. Global Body Styles 
         - bg-black: Ensures the whole app is dark mode by default
         - text-white: Default text color
         - antialiased: Makes fonts look sharp 
      */}
      <body className={`${inter.className} bg-black text-white antialiased`}>
        {children}
      </body>
    </html>
  )
}