// // ---------------------------------------------------------
// // 1. PROJECT
// // ---------------------------------------------------------
// export interface Project {
//   id: string; // UUID
//   name: string;
//   description?: string;
//   base_url?: string;
//   github_repo_url?: string;
//   api_key?: string;      // Optional: if you decide to store it on the project
//   webhook_secret?: string; 
//   created_at: string;    // ISO Date String
// }

// // ---------------------------------------------------------
// // 2. SECRETS (Environment Variables)
// // ---------------------------------------------------------
// export interface Secret {
//   id: string;
//   project_id: string;
//   key: string;           // e.g. "OPENAI_API_KEY"
//   value_masked: string;  // e.g. "********sk1"
//   created_at: string;
// }

// // ---------------------------------------------------------
// // 3. API SPECS / VERSIONS
// // ---------------------------------------------------------
// export interface ApiVersion {
//   id: string;
//   project_id: string;
//   version: string;       // e.g. "v1.0"
//   status: 'PENDING' | 'PARSING' | 'READY' | 'FAILED';
//   spec_json?: any;       // The parsed Swagger/OpenAPI JSON
//   created_at: string;
// }

// // ---------------------------------------------------------
// // 4. TEST BLUEPRINTS (The AI Plan)
// // ---------------------------------------------------------
// export interface TestBlueprint {
//   id: string;
//   api_version_id: string;
//   status: 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED';
//   summary?: string;
//   ai_strategy_json: any; // The logic/plan generated by Gemini
//   created_at: string;
//   approved_at?: string;
//   approved_by?: string;
// }

// // ---------------------------------------------------------
// // 5. TEST RUNS (Execution Results)
// // ---------------------------------------------------------
// export interface TestRun {
//   id: string;
//   blueprint_id: string;
//   status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'PASSED';
//   result_json?: any;     // The actual results from the test runner
//   logs?: LogEntry[];     // Optional: If we fetch full details
//   created_at: string;
//   completed_at?: string;
// }

// // ---------------------------------------------------------
// // 6. UTILITIES
// // ---------------------------------------------------------
// export interface LogEntry {
//   timestamp: string;
//   level: 'INFO' | 'WARN' | 'ERROR' | 'PASS' | 'FAIL';
//   message: string;
// }

// export interface User {
//   id: string;
//   email: string;
//   full_name?: string;
// }


// ---------------------------------------------------------
// 1. PROJECT
// ---------------------------------------------------------
export interface Project {
  id: string;
  name: string;
  description?: string;
  base_url?: string;
  github_repo_url?: string;
  created_at: string;
}

// ---------------------------------------------------------
// 2. SECRETS (Secret Vault)
// ---------------------------------------------------------
export interface Secret {
  id: string;
  project_id: string;
  key_name: string;        // matches backend
  environment: 'DEV' | 'STAGING' | 'PROD';
  scope: 'PROJECT' | 'GLOBAL';
  is_active: boolean;
  created_at: string;
}

// ---------------------------------------------------------
// 3. API VERSIONS
// ---------------------------------------------------------
export interface ApiVersion {
  status(status: any): import("react").ReactNode;
  id: string;
  project_id: string;
  version?: string;
  spec_json?: any;
  created_at: string;
}

// ---------------------------------------------------------
// 4. TEST BLUEPRINTS
// ---------------------------------------------------------
export interface TestBlueprint {
  id: string;
  api_version_id: string;
  status: 'PENDING_APPROVAL' | 'APPROVED' | 'REJECTED';
  summary?: string;
  ai_strategy_json: any;
  created_at: string;
  approved_at?: string;
  approved_by?: string;
}

// ---------------------------------------------------------
// 5. TEST RUNS
// ---------------------------------------------------------
export interface TestRun {
  finished_at: string | undefined;
  id: string;
  blueprint_id: string;
  status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'PASSED';
  result_json?: any;
  created_at: string;
  completed_at?: string;
}

// ---------------------------------------------------------
// 6. LOGGING
// ---------------------------------------------------------
export interface LogEntry {
  timestamp: string;
  level: 'INFO' | 'WARN' | 'ERROR' | 'PASS' | 'FAIL';
  message: string;
}

// ---------------------------------------------------------
// 7. AUTH (Future-ready)
// ---------------------------------------------------------
export interface User {
  id: string;
  email: string;
  full_name?: string;
}
